# Generated by Django 3.0.5 on 2020-04-15 04:53

from django.db import migrations, models
import localflavor.br.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, verbose_name='CNPJ')),
                ('razao', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('estado', localflavor.br.models.BRStateField(max_length=2, verbose_name='Estado')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', phone_field.models.PhoneField(max_length=15, verbose_name='Telefone')),
            ],
        ),
    ]
