# Generated by Django 3.0.5 on 2020-04-24 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_auto_20200423_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaempenho',
            name='descricao',
            field=models.CharField(default=0, max_length=16, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='observacao',
            field=models.CharField(default=0, max_length=255, verbose_name='Observacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='prazoEntrega',
            field=models.CharField(default=0, max_length=20, verbose_name='PrazoEntrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='requerente',
            field=models.CharField(default='CGA', max_length=4, verbose_name='Requerente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='saldo',
            field=models.FloatField(default=0, verbose_name='Saldo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='valor',
            field=models.FloatField(default=0, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorPago', models.FloatField(verbose_name='ValorPago')),
                ('dataPagamento', models.DateField(auto_now_add=True, verbose_name='DataPag')),
                ('notaFiscal', models.IntegerField(verbose_name='NotaFiscal')),
                ('processo', models.CharField(max_length=20, verbose_name='Processo')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='materiais.Fornecedor')),
                ('ne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.NotaEmpenho')),
            ],
        ),
    ]
