# Generated by Django 3.0.5 on 2020-04-16 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_notaempenho_ne'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaempenho',
            name='prazo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notaempenho',
            name='requerente',
            field=models.CharField(default=0, max_length=4, verbose_name='REQUERENTE'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.FloatField(verbose_name='valor')),
                ('data', models.DateField(auto_now=True, verbose_name='data')),
                ('nfe', models.IntegerField(verbose_name='nota fiscal')),
                ('processo', models.CharField(max_length=20, verbose_name='processo')),
                ('ne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='materiais.NotaEmpenho')),
            ],
        ),
    ]
